### ISSUE TITLE
Error / Maybe Incompatibilizy with Mod "Packing Tape"?

### ISSUE THREAD

**Issue by Vystella** [lmst2/Fridge#2]
Hi, when i pickup a Fridge with some Items in it and the mod "Packing Tape" with Toggle-Mode is active i get the folloeing error:

Die Mod Fridge (0.0.9) hat einen Fehler verursacht, der nicht behoben werden kann.
Bitte informiere den Autor der Mod über diesen Fehler.

Error while running event Fridge::on_tick (ID 0)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__Fridge__/control.lua:73: in function 'check_fridges'
	__Fridge__/control.lua:106: in function <__Fridge__/control.lua:99>

https://www.youtube.com/watch?v=Ev6NIdMgJKU

Idk, depends the Issue on your mod or on the other?

**Comment by lmst2** [comment]
looks like the get_inventory() method is failling. when you remove the fridge, the fridge does't exist anymore, this is why falling, but that's wired, cause when you remove the firdge, this should trigger the code to remove the fridge from watching list. I will add a gard to prevent this from happening. today or tomorrow.

**Comment by lmst2** [comment]
i see, the mod you are using maybe keeps the fridge entity since it was not actually 'removed' so it is not triggering my function to remove it from the list. but when you pick it up, the frideg entity becomes 'invalid' so i can't get its iventory. not sure what the mod dose. need to find out if its safe to ignore it, cause then what happens when you put that fridge back down. if it puts another new fridge entity then I will have a dead fridge entity in my watching list this is not i want. but if i removes the old firdge, then when you put it back down only reenable it. then that fridge wont work anymore. this taks time to find out. will work on that

**Comment by Vystella** [comment]
Ah, okay. So take your time, because seems to happens only when Toggle Function is activated, and these are easily deactivated.
(And my reorganisation on Gleba is done)
Dont know if that happens on the "warehouse" of the mod too, for the warehouse i need kryo science and im just start beginning on Aquilo. But if i can help you with testing something, just tell me.

**Comment by lmst2** [comment]
no worries I will download that mod and test it out.

**Comment by lmst2** [comment]
![image](https://github.com/user-attachments/assets/3ea025d1-d02c-47ba-9147-5c3300fd9416)
![image](https://github.com/user-attachments/assets/fb201006-df88-4978-976e-914b916c966c)
I knows why, I looked in the code of packing tape, and sees it destroys my fridge entity when packing. but it doesn't raised the event, so in my code, although I am listening this event, I still haven't hear my fridge is destroyed, because they haven't sent that event initially. according to the official document, the event is default to not sending the signal. witch is wired, why? it should send the signal until explicitly set to silent. that is what make sense instead.

**Comment by lmst2** [comment]
now that should fixed

**Comment by Vystella** [comment]
Mod Updated but when i load my save i get this error (maybe a new one?):

Die Mod Fridge (0.0.10) hat einen Fehler verursacht, der nicht behoben werden kann.
Bitte informiere den Autor der Mod über diesen Fehler.

Error while running event Fridge::on_tick (ID 0)
spoil_tick can not be set to longer than the item's normal spoil ticks.
stack traceback:
	[C]: in function '__newindex'
	__Fridge__/control.lua:82: in function 'check_fridges'
	__Fridge__/control.lua:104: in function <__Fridge__/control.lua:97>

After a few seconds, 0.0.11 released, but Error is still prsent only Line Changes

Die Mod Fridge (0.0.11) hat einen Fehler verursacht, der nicht behoben werden kann.
Bitte informiere den Autor der Mod über diesen Fehler.

Error while running event Fridge::on_tick (ID 0)
spoil_tick can not be set to longer than the item's normal spoil ticks.
stack traceback:
	[C]: in function '__newindex'
	__Fridge__/control.lua:83: in function 'check_fridges'
	__Fridge__/control.lua:105: in function <__Fridge__/control.lua:98>

Next Edit: 
I think depends on my fault. Spoilage Time of Nutrients and Science was set to 0 ( None) with another mod.
When i changed this back to normal, Save is started without an error.

**Comment by lmst2** [comment]
>I think depends on my fault. Spoilage Time of Nutrients and Science was set to 0 ( None) with another mod.
>When i changed this back to normal, Save is started without an error.

may be you need to pick the fridge up and put it back again to make it work in the old save. dont know why that happens. and also, in my mod, I ignore all items with 0 spoil time. because that means it wont spoil at all. so technically it shouldn't causing any problem by editing it with other mods. but it really depends on how other mod behaves.

**Comment by Vystella** [comment]
> > I think depends on my fault. Spoilage Time of Nutrients and Science was set to 0 ( None) with another mod.
> > When i changed this back to normal, Save is started without an error.
> 
> may be you need to pick the fridge up and put it back again to make it work in the old save. dont know why that happens. and also, in my mod, I ignore all items with 0 spoil time. because that means it wont spoil at all. so technically it shouldn't causing any problem by editing it with other mods. but it really depends on how other mod behaves.

Pick up th fridge is not possible, bc save is loaded and immediately the error occurs and the game crashes.
After some tests i find out, is only happens when i set the spoilage of the science pack to zero. And doesnt matter which mod that does, i had tested this with 3 mods that disables the spoilage.
With all other items e.g. nutrients bioflux biter eggs works fine.
For now i had activated the spoilage of the science pack, so i can continue my savefame.

**Comment by lmst2** [comment]
okey, then it might be some hard limit on science pack. maybe they does not want you to set it to zero.
